# Generated by Django 4.1.5 on 2023-01-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='item',
            new_name='book',
        ),
    ]
